
/*
 * GET home page.
 */

exports.index = function(req, res){
  res.render('index', {

    title:"hooraayyy",

    tiles: [
      {heading: "Sushi Chef, Chef Helper, and Servers Wanted (dublin / pleasanton / livermore)", content: "Zakuro Japanese Bistro & Sushi Bar is looking for customer service oriented sushi chefs, chef assistants, and servers to start immediately. Previous experience is preferable. We will start contacting eligible candidates right away. To apply please email your resume, phone number and availability to hello[at]zakurobistro.com or reply to this posting."},
      {heading: "Sr. Visual Designer @ Scribd (SOMA / south beach)", content: "Scribd is a technology company in San Francisco building the world's online library. Scribd has raised $26M, is profitable, and is one of the largest sites on the web, but it is still run by a comparatively small team and still in the very early stages of achieving our vision for what the library of the future could be. We recently launched a subscription service that is widely being called the first 'Netflix for books' and we're very excited about it."},
      {heading: "Math/Science teacher, Spanish Teacher, Preschool Teacher ", content: "We are a small school located in a beautiful neighborhood in West San Jose. We offer a well rounded program with a challenging curriculum and lots of rigor during school hours. If you are a motivated, organized and focused individual who meets the following requirements, we would love to hear from you."},
      {heading: "Sushi Chef, Chef Helper, and Servers Wanted (dublin / pleasanton / livermore)", content: "Zakuro Japanese Bistro & Sushi Bar is looking for customer service oriented sushi chefs, chef assistants, and servers to start immediately. Previous experience is preferable. We will start contacting eligible candidates right away. To apply please email your resume, phone number and availability to hello[at]zakurobistro.com or reply to this posting."},
      {heading: "Sr. Visual Designer @ Scribd (SOMA / south beach)", content: "Scribd is a technology company in San Francisco building the world's online library. Scribd has raised $26M, is profitable, and is one of the largest sites on the web, but it is still run by a comparatively small team and still in the very early stages of achieving our vision for what the library of the future could be. We recently launched a subscription service that is widely being called the first 'Netflix for books' and we're very excited about it."},
      {heading: "Math/Science teacher, Spanish Teacher, Preschool Teacher ", content: "We are a small school located in a beautiful neighborhood in West San Jose. We offer a well rounded program with a challenging curriculum and lots of rigor during school hours. If you are a motivated, organized and focused individual who meets the following requirements, we would love to hear from you."},
      {heading: "Sr. Visual Designer @ Scribd (SOMA / south beach)", content: "Scribd is a technology company in San Francisco building the world's online library. Scribd has raised $26M, is profitable, and is one of the largest sites on the web, but it is still run by a comparatively small team and still in the very early stages of achieving our vision for what the library of the future could be. We recently launched a subscription service that is widely being called the first 'Netflix for books' and we're very excited about it."},
      {heading: "Math/Science teacher, Spanish Teacher, Preschool Teacher ", content: "We are a small school located in a beautiful neighborhood in West San Jose. We offer a well rounded program with a challenging curriculum and lots of rigor during school hours. If you are a motivated, organized and focused individual who meets the following requirements, we would love to hear from you."},
      {heading: "Sushi Chef, Chef Helper, and Servers Wanted (dublin / pleasanton / livermore)", content: "Zakuro Japanese Bistro & Sushi Bar is looking for customer service oriented sushi chefs, chef assistants, and servers to start immediately. Previous experience is preferable. We will start contacting eligible candidates right away. To apply please email your resume, phone number and availability to hello[at]zakurobistro.com or reply to this posting."},
      {heading: "Sr. Visual Designer @ Scribd (SOMA / south beach)", content: "Scribd is a technology company in San Francisco building the world's online library. Scribd has raised $26M, is profitable, and is one of the largest sites on the web, but it is still run by a comparatively small team and still in the very early stages of achieving our vision for what the library of the future could be. We recently launched a subscription service that is widely being called the first 'Netflix for books' and we're very excited about it."}

      ]
  });
};